### ISSUE TITLE
Result of compute_border_array() disagrees with text.

### ISSUE THREAD

**Issue by ghost** [Apress/string-algorithms-in-c#1]
On page 15, the text reads as follows:

> Consider x=ababa. For index 0 we have string a which has border a, so the first element in the border array is 1. 

The text says the complete border array for string x=ababa is ba=[1, 0, 1, 2, 3]. 

However, when I run the compute_border_array() function on the string "ababa", I get a border array result of: [0, 0, 1, 2, 3]. 

In general, the paragraph on page 15 is very confusing and I think it has at least one editing mistake. The last sentence of the paragraph reads as follows:

> The full string x=ababa with border aba so its border array looks like ba=[1, 0, 1, 2, 3]. 

This sentence isn't even grammatically correct. 

For the substring "ab", the text says it has only the "trivial, **nonempty** border, so the border array value is zero." I added the emphasis on "nonempty". Shouldn't this text say the result is the trivial, **empty** string?

Thanks, and sorry for the confusion if I'm missing something obvious... 
-J

**Comment by mailund** [comment]
Sorry, yes that does seem to be errors. The border array for "ababa" is [0, 0, 1, 2, 3]. There is only the empty border for "a" and "ab", then there is the border "a" for "aba", "ab" for "abab", and finally "aba" for "ababa". So, "aba" is the border for the full string.

The "ab" string only has the empty border, and its border array is [0, 0].

Sorry for the confusion.

**Comment by ghost** [comment]
Hi thanks for clearing that up, I was pretty sure the code was correct and the text had the error. 
Thanks again, 
-J
